# Generated by Django 3.1 on 2020-08-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RcStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('birthday', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('qq_number', models.CharField(max_length=20, null=True)),
                ('photo', models.CharField(max_length=50, null=True)),
                ('major', models.CharField(max_length=50, null=True)),
                ('subject', models.CharField(max_length=70, null=True)),
                ('intro', models.TextField(null=True)),
            ],
        ),
    ]
